### ISSUE TITLE
spring-mvc

### ISSUE THREAD

**Issue by vzhyhunou** [vzhyhunou/Viktar-Zhyhunou-Group-1#8]
See JSP exception when customers page opens:
org.apache.jasper.JasperException: /WEB-INF/pages/customers.jsp(13,8) The function getName must be used with a prefix when a default namespace is not specified

and 

org.apache.jasper.JasperException: /WEB-INF/pages/customer.jsp(20,33) The function getId must be used with a prefix when a default namespace is not specified
when costumer should be found by id

**Comment by AliaksandrDarafeyeu** [comment]
I made new commit
